// Autogenerated code by vite-plugin-svg-sprite-names-typescript
export type IconName = "nuxt" | "typescript" | "vite" | "vue";
export const IconNameList = ["nuxt", "typescript", "vite", "vue"] as const;
